[build]
  command = "pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "pnpm dev"

[functions]
  included_files = ["!**/*.md"]

# Disable secrets scanning for specific keys since they are required for client-side Supabase integration
[secrets]
  scan = true
  omit_keys = [
    "NEXT_PUBLIC_SUPABASE_URL", 
    "NEXT_PUBLIC_SUPABASE_ANON_KEY",
    "SUPABASE_SERVICE_ROLE_KEY",
    "SEED_TOKEN"
  ]